services:
  app:
    build: .
    container_name: codescript-backend
    ports:
      - "8000:80"  # Expose port 8000 on host, mapped to port 80 in the container
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Using environment variable for database connection
    volumes:
      - .:/app  # Mount current directory to /app in the container (for development)
    depends_on:
      - db  # Ensures MySQL starts before FastAPI
  
  db:
    image: mysql:8.0
    container_name: codescript-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: codescript_db  
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    ports:
      - "3306:3306"  # Expose MySQL port for access

volumes:
  mysql_data:  # Define a volume for MySQL data persistence
