services:
  api:
    build: .
    container_name: codescript-fastapi
    ports:
      - "8000:80"
    environment:
      - DOCKER_DATABASE_URL=${DOCKER_DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - codescript_network

networks:
  codescript_network:
    external: true
