services:
  api:
    container_name: codescript-backend
    build: .
    volumes:
      - .:/app
    environment:
      - DOCKER_DATABASE_URL=${DOCKER_DATABASE_URL:-}
      - GCP_CREDENTIALS=${GCP_CREDENTIALS:-}
      - GC_BUCKET_NAME=${GC_BUCKET_NAME:-}
    networks:
      - codescript_network
    ports:
      - "8000:8000"

networks:
  codescript_network:
    external: true
