services:
  backend:
    container_name: codescript-backend
    build: .
    volumes:
      - .:/app
    environment:
      - DOCKER_DATABASE_URL=${DOCKER_DATABASE_URL:-}
      - GCP_CREDENTIALS=${GCP_CREDENTIALS:-}
      - GC_BUCKET_NAME=${GC_BUCKET_NAME:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
      - DEMO_MODE=${DEMO_MODE:-}
    networks:
      - codescript_network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]

  frontend:
    container_name: codescript-frontend
    build:
      context: ../codescript-frontend
      args:
        - VITE_RANDOM_PROBLEM_URL=${VITE_RANDOM_PROBLEM_URL}
        - VITE_GENERATE_FEEDBACK_URL=${VITE_GENERATE_FEEDBACK_URL}
    env_file: 
      - .env
    networks:
      - codescript_network
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy

networks:
  codescript_network:
    external: true
