"""Update Problem generating signed image urls

Revision ID: 363175fd66e2
Revises: ec0111bcc519
Create Date: 2025-03-05 17:57:07.607132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '363175fd66e2'
down_revision: Union[str, None] = 'ec0111bcc519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('image_paths', sa.JSON(), nullable=False))
    op.drop_column('problems', 'image_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('image_urls', mysql.JSON(), nullable=False))
    op.drop_column('problems', 'image_paths')
    # ### end Alembic commands ###
