"""Remove Submission association with Problem

Revision ID: 743e9ea660e2
Revises: f94d85ab4427
Create Date: 2025-02-27 18:20:03.044983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743e9ea660e2'
down_revision: Union[str, None] = 'f94d85ab4427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
