"""Update Problem model 'example' field to 'examples'

Revision ID: a78f7d5e2f0c
Revises: 8100c2f29675
Create Date: 2025-01-20 18:10:33.668408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a78f7d5e2f0c'
down_revision: Union[str, None] = '8100c2f29675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('examples', sa.JSON(), nullable=False))
    op.drop_column('problems', 'example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('example', mysql.JSON(), nullable=False))
    op.drop_column('problems', 'examples')
    # ### end Alembic commands ###
