"""Change Problem constrains field from string to a list of strings

Revision ID: ec0111bcc519
Revises: 743e9ea660e2
Create Date: 2025-03-05 09:23:53.455319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec0111bcc519'
down_revision: Union[str, None] = '743e9ea660e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'constraints',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'constraints',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
